// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `emit_event`, `mutation_lock`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

void initDb({required String path}) =>
    RustLib.instance.api.crateApiInitDb(path: path);

void openBox({required String name, String? encryptionKey}) =>
    RustLib.instance.api
        .crateApiOpenBox(name: name, encryptionKey: encryptionKey);

void closeBox({required String name}) =>
    RustLib.instance.api.crateApiCloseBox(name: name);

void deleteBox({required String name}) =>
    RustLib.instance.api.crateApiDeleteBox(name: name);

void encryptBox({required String name, required String encryptionKey}) =>
    RustLib.instance.api
        .crateApiEncryptBox(name: name, encryptionKey: encryptionKey);

bool boxExists({required String name}) =>
    RustLib.instance.api.crateApiBoxExists(name: name);

Future<Stream<NativeBoxEvent>> watchBox(
        {required String boxName, required String watcherId}) =>
    RustLib.instance.api
        .crateApiWatchBox(boxName: boxName, watcherId: watcherId);

void unwatchBox({required String boxName, required String watcherId}) =>
    RustLib.instance.api
        .crateApiUnwatchBox(boxName: boxName, watcherId: watcherId);

Future<void> put(
        {required String boxName,
        required String key,
        required List<int> value}) =>
    RustLib.instance.api.crateApiPut(boxName: boxName, key: key, value: value);

Future<void> putAll(
        {required String boxName,
        required List<(String, Uint8List)> entries}) =>
    RustLib.instance.api.crateApiPutAll(boxName: boxName, entries: entries);

Future<Uint8List?> get_({required String boxName, required String key}) =>
    RustLib.instance.api.crateApiGet(boxName: boxName, key: key);

Future<bool> containsKey({required String boxName, required String key}) =>
    RustLib.instance.api.crateApiContainsKey(boxName: boxName, key: key);

Future<void> delete({required String boxName, required String key}) =>
    RustLib.instance.api.crateApiDelete(boxName: boxName, key: key);

Future<List<String>> deleteAll(
        {required String boxName, required List<String> keys}) =>
    RustLib.instance.api.crateApiDeleteAll(boxName: boxName, keys: keys);

Future<void> clear({required String boxName}) =>
    RustLib.instance.api.crateApiClear(boxName: boxName);

Future<bool> compact({required String boxName}) =>
    RustLib.instance.api.crateApiCompact(boxName: boxName);

Future<List<String>> getAllKeys({required String boxName}) =>
    RustLib.instance.api.crateApiGetAllKeys(boxName: boxName);

Future<BigInt> length({required String boxName}) =>
    RustLib.instance.api.crateApiLength(boxName: boxName);

class NativeBoxEvent {
  final String boxName;
  final NativeBoxEventType eventType;
  final String? key;
  final Uint8List? value;

  const NativeBoxEvent({
    required this.boxName,
    required this.eventType,
    this.key,
    this.value,
  });

  @override
  int get hashCode =>
      boxName.hashCode ^ eventType.hashCode ^ key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeBoxEvent &&
          runtimeType == other.runtimeType &&
          boxName == other.boxName &&
          eventType == other.eventType &&
          key == other.key &&
          value == other.value;
}

enum NativeBoxEventType {
  put,
  delete,
  clear,
  ;
}
