// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void initDb({required String path}) =>
    RustLib.instance.api.crateApiInitDb(path: path);

void openBox({required String name, String? encryptionKey}) =>
    RustLib.instance.api
        .crateApiOpenBox(name: name, encryptionKey: encryptionKey);

void closeBox({required String name}) =>
    RustLib.instance.api.crateApiCloseBox(name: name);

void deleteBox({required String name}) =>
    RustLib.instance.api.crateApiDeleteBox(name: name);

bool boxExists({required String name}) =>
    RustLib.instance.api.crateApiBoxExists(name: name);

Future<void> put(
        {required String boxName,
        required String key,
        required List<int> value}) =>
    RustLib.instance.api.crateApiPut(boxName: boxName, key: key, value: value);

Future<void> putAll(
        {required String boxName,
        required List<(String, Uint8List)> entries}) =>
    RustLib.instance.api.crateApiPutAll(boxName: boxName, entries: entries);

Future<Uint8List?> get_({required String boxName, required String key}) =>
    RustLib.instance.api.crateApiGet(boxName: boxName, key: key);

Future<bool> containsKey({required String boxName, required String key}) =>
    RustLib.instance.api.crateApiContainsKey(boxName: boxName, key: key);

Future<void> delete({required String boxName, required String key}) =>
    RustLib.instance.api.crateApiDelete(boxName: boxName, key: key);

Future<void> clear({required String boxName}) =>
    RustLib.instance.api.crateApiClear(boxName: boxName);

Future<List<String>> getAllKeys({required String boxName}) =>
    RustLib.instance.api.crateApiGetAllKeys(boxName: boxName);

Future<BigInt> length({required String boxName}) =>
    RustLib.instance.api.crateApiLength(boxName: boxName);
