// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.8.0';

  @override
  int get rustContentHash => -1101866808;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_dxtr_box',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  bool crateApiBoxExists({required String name});

  Future<void> crateApiClear({required String boxName});

  void crateApiCloseBox({required String name});

  Future<bool> crateApiCompact({required String boxName});

  bool crateApiContainsKey({required String boxName, required String key});

  Future<void> crateApiCreateIndex(
      {required String boxName, required String name, required String field});

  Future<void> crateApiDelete({required String boxName, required String key});

  Future<List<String>> crateApiDeleteAll(
      {required String boxName, required List<String> keys});

  void crateApiDeleteBox({required String name});

  Future<bool> crateApiDropIndex(
      {required String boxName, required String name});

  void crateApiEncryptBox(
      {required String name, required String encryptionKey});

  Uint8List? crateApiGet({required String boxName, required String key});

  Future<List<String>> crateApiGetAllKeys({required String boxName});

  void crateApiInitDb({required String path});

  Future<BigInt> crateApiLength({required String boxName});

  Future<List<NativeIndexDefinition>> crateApiListIndexes(
      {required String boxName});

  void crateApiOpenBox({required String name, String? encryptionKey});

  Future<void> crateApiPut(
      {required String boxName, required String key, required List<int> value});

  Future<void> crateApiPutAll(
      {required String boxName, required List<(String, Uint8List)> entries});

  Future<List<NativeQueryRecord>> crateApiScanQuery(
      {required String boxName, required List<int> queryPayload});

  void crateApiUnwatchBox({required String boxName, required String watcherId});

  Future<Stream<NativeBoxEvent>> crateApiWatchBox(
      {required String boxName, required String watcherId});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  bool crateApiBoxExists({required String name}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBoxExistsConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBoxExistsConstMeta => const TaskConstMeta(
        debugName: "box_exists",
        argNames: ["name"],
      );

  @override
  Future<void> crateApiClear({required String boxName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(boxName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiClearConstMeta,
      argValues: [boxName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClearConstMeta => const TaskConstMeta(
        debugName: "clear",
        argNames: ["boxName"],
      );

  @override
  void crateApiCloseBox({required String name}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCloseBoxConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCloseBoxConstMeta => const TaskConstMeta(
        debugName: "close_box",
        argNames: ["name"],
      );

  @override
  Future<bool> crateApiCompact({required String boxName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(boxName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCompactConstMeta,
      argValues: [boxName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCompactConstMeta => const TaskConstMeta(
        debugName: "compact",
        argNames: ["boxName"],
      );

  @override
  bool crateApiContainsKey({required String boxName, required String key}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(boxName, serializer);
        sse_encode_String(key, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiContainsKeyConstMeta,
      argValues: [boxName, key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiContainsKeyConstMeta => const TaskConstMeta(
        debugName: "contains_key",
        argNames: ["boxName", "key"],
      );

  @override
  Future<void> crateApiCreateIndex(
      {required String boxName, required String name, required String field}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(boxName, serializer);
        sse_encode_String(name, serializer);
        sse_encode_String(field, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCreateIndexConstMeta,
      argValues: [boxName, name, field],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCreateIndexConstMeta => const TaskConstMeta(
        debugName: "create_index",
        argNames: ["boxName", "name", "field"],
      );

  @override
  Future<void> crateApiDelete({required String boxName, required String key}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(boxName, serializer);
        sse_encode_String(key, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDeleteConstMeta,
      argValues: [boxName, key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeleteConstMeta => const TaskConstMeta(
        debugName: "delete",
        argNames: ["boxName", "key"],
      );

  @override
  Future<List<String>> crateApiDeleteAll(
      {required String boxName, required List<String> keys}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(boxName, serializer);
        sse_encode_list_String(keys, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDeleteAllConstMeta,
      argValues: [boxName, keys],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeleteAllConstMeta => const TaskConstMeta(
        debugName: "delete_all",
        argNames: ["boxName", "keys"],
      );

  @override
  void crateApiDeleteBox({required String name}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDeleteBoxConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeleteBoxConstMeta => const TaskConstMeta(
        debugName: "delete_box",
        argNames: ["name"],
      );

  @override
  Future<bool> crateApiDropIndex(
      {required String boxName, required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(boxName, serializer);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDropIndexConstMeta,
      argValues: [boxName, name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDropIndexConstMeta => const TaskConstMeta(
        debugName: "drop_index",
        argNames: ["boxName", "name"],
      );

  @override
  void crateApiEncryptBox(
      {required String name, required String encryptionKey}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        sse_encode_String(encryptionKey, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiEncryptBoxConstMeta,
      argValues: [name, encryptionKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEncryptBoxConstMeta => const TaskConstMeta(
        debugName: "encrypt_box",
        argNames: ["name", "encryptionKey"],
      );

  @override
  Uint8List? crateApiGet({required String boxName, required String key}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(boxName, serializer);
        sse_encode_String(key, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetConstMeta,
      argValues: [boxName, key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetConstMeta => const TaskConstMeta(
        debugName: "get",
        argNames: ["boxName", "key"],
      );

  @override
  Future<List<String>> crateApiGetAllKeys({required String boxName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(boxName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetAllKeysConstMeta,
      argValues: [boxName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetAllKeysConstMeta => const TaskConstMeta(
        debugName: "get_all_keys",
        argNames: ["boxName"],
      );

  @override
  void crateApiInitDb({required String path}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiInitDbConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitDbConstMeta => const TaskConstMeta(
        debugName: "init_db",
        argNames: ["path"],
      );

  @override
  Future<BigInt> crateApiLength({required String boxName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(boxName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLengthConstMeta,
      argValues: [boxName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLengthConstMeta => const TaskConstMeta(
        debugName: "length",
        argNames: ["boxName"],
      );

  @override
  Future<List<NativeIndexDefinition>> crateApiListIndexes(
      {required String boxName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(boxName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_native_index_definition,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiListIndexesConstMeta,
      argValues: [boxName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiListIndexesConstMeta => const TaskConstMeta(
        debugName: "list_indexes",
        argNames: ["boxName"],
      );

  @override
  void crateApiOpenBox({required String name, String? encryptionKey}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        sse_encode_opt_String(encryptionKey, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiOpenBoxConstMeta,
      argValues: [name, encryptionKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOpenBoxConstMeta => const TaskConstMeta(
        debugName: "open_box",
        argNames: ["name", "encryptionKey"],
      );

  @override
  Future<void> crateApiPut(
      {required String boxName,
      required String key,
      required List<int> value}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(boxName, serializer);
        sse_encode_String(key, serializer);
        sse_encode_list_prim_u_8_loose(value, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiPutConstMeta,
      argValues: [boxName, key, value],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPutConstMeta => const TaskConstMeta(
        debugName: "put",
        argNames: ["boxName", "key", "value"],
      );

  @override
  Future<void> crateApiPutAll(
      {required String boxName, required List<(String, Uint8List)> entries}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(boxName, serializer);
        sse_encode_list_record_string_list_prim_u_8_strict(entries, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiPutAllConstMeta,
      argValues: [boxName, entries],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPutAllConstMeta => const TaskConstMeta(
        debugName: "put_all",
        argNames: ["boxName", "entries"],
      );

  @override
  Future<List<NativeQueryRecord>> crateApiScanQuery(
      {required String boxName, required List<int> queryPayload}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(boxName, serializer);
        sse_encode_list_prim_u_8_loose(queryPayload, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_native_query_record,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiScanQueryConstMeta,
      argValues: [boxName, queryPayload],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiScanQueryConstMeta => const TaskConstMeta(
        debugName: "scan_query",
        argNames: ["boxName", "queryPayload"],
      );

  @override
  void crateApiUnwatchBox(
      {required String boxName, required String watcherId}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(boxName, serializer);
        sse_encode_String(watcherId, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiUnwatchBoxConstMeta,
      argValues: [boxName, watcherId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUnwatchBoxConstMeta => const TaskConstMeta(
        debugName: "unwatch_box",
        argNames: ["boxName", "watcherId"],
      );

  @override
  Future<Stream<NativeBoxEvent>> crateApiWatchBox(
      {required String boxName, required String watcherId}) async {
    final sink = RustStreamSink<NativeBoxEvent>();
    await handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(boxName, serializer);
        sse_encode_String(watcherId, serializer);
        sse_encode_StreamSink_native_box_event_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiWatchBoxConstMeta,
      argValues: [boxName, watcherId, sink],
      apiImpl: this,
    ));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiWatchBoxConstMeta => const TaskConstMeta(
        debugName: "watch_box",
        argNames: ["boxName", "watcherId", "sink"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<NativeBoxEvent> dco_decode_StreamSink_native_box_event_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<NativeIndexDefinition> dco_decode_list_native_index_definition(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_native_index_definition)
        .toList();
  }

  @protected
  List<NativeQueryRecord> dco_decode_list_native_query_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_native_query_record).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, Uint8List)> dco_decode_list_record_string_list_prim_u_8_strict(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_string_list_prim_u_8_strict)
        .toList();
  }

  @protected
  NativeBoxEvent dco_decode_native_box_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return NativeBoxEvent(
      boxName: dco_decode_String(arr[0]),
      eventType: dco_decode_native_box_event_type(arr[1]),
      key: dco_decode_opt_String(arr[2]),
      value: dco_decode_opt_list_prim_u_8_strict(arr[3]),
    );
  }

  @protected
  NativeBoxEventType dco_decode_native_box_event_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NativeBoxEventType.values[raw as int];
  }

  @protected
  NativeIndexDefinition dco_decode_native_index_definition(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NativeIndexDefinition(
      name: dco_decode_String(arr[0]),
      field: dco_decode_String(arr[1]),
    );
  }

  @protected
  NativeQueryRecord dco_decode_native_query_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NativeQueryRecord(
      key: dco_decode_String(arr[0]),
      value: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  (String, Uint8List) dco_decode_record_string_list_prim_u_8_strict(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<NativeBoxEvent> sse_decode_StreamSink_native_box_event_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<NativeIndexDefinition> sse_decode_list_native_index_definition(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NativeIndexDefinition>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_native_index_definition(deserializer));
    }
    return ans_;
  }

  @protected
  List<NativeQueryRecord> sse_decode_list_native_query_record(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NativeQueryRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_native_query_record(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, Uint8List)> sse_decode_list_record_string_list_prim_u_8_strict(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, Uint8List)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  NativeBoxEvent sse_decode_native_box_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_boxName = sse_decode_String(deserializer);
    var var_eventType = sse_decode_native_box_event_type(deserializer);
    var var_key = sse_decode_opt_String(deserializer);
    var var_value = sse_decode_opt_list_prim_u_8_strict(deserializer);
    return NativeBoxEvent(
        boxName: var_boxName,
        eventType: var_eventType,
        key: var_key,
        value: var_value);
  }

  @protected
  NativeBoxEventType sse_decode_native_box_event_type(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return NativeBoxEventType.values[inner];
  }

  @protected
  NativeIndexDefinition sse_decode_native_index_definition(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_field = sse_decode_String(deserializer);
    return NativeIndexDefinition(name: var_name, field: var_field);
  }

  @protected
  NativeQueryRecord sse_decode_native_query_record(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_String(deserializer);
    var var_value = sse_decode_list_prim_u_8_strict(deserializer);
    return NativeQueryRecord(key: var_key, value: var_value);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, Uint8List) sse_decode_record_string_list_prim_u_8_strict(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_list_prim_u_8_strict(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_native_box_event_Sse(
      RustStreamSink<NativeBoxEvent> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_native_box_event,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_native_index_definition(
      List<NativeIndexDefinition> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_native_index_definition(item, serializer);
    }
  }

  @protected
  void sse_encode_list_native_query_record(
      List<NativeQueryRecord> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_native_query_record(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_list_prim_u_8_strict(
      List<(String, Uint8List)> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_native_box_event(
      NativeBoxEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.boxName, serializer);
    sse_encode_native_box_event_type(self.eventType, serializer);
    sse_encode_opt_String(self.key, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.value, serializer);
  }

  @protected
  void sse_encode_native_box_event_type(
      NativeBoxEventType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_native_index_definition(
      NativeIndexDefinition self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.field, serializer);
  }

  @protected
  void sse_encode_native_query_record(
      NativeQueryRecord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.key, serializer);
    sse_encode_list_prim_u_8_strict(self.value, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_list_prim_u_8_strict(
      (String, Uint8List) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_list_prim_u_8_strict(self.$2, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
